export enum ReqMethod {
  GET = "GET",
  POST = "POST",
  PATCH = "PATCH",
  PUT = "PUT",
  DELETE = "DELETE",
}

export enum HttpStatus {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,

  REDIRECT = 307,

  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  PAYLOAD_TOO_LARGE = 413,
  UNSUPPORTED_MEDIA_FORMAT = 415,
  EXPECTATION_FAILED = 417,
  UNPROCESSABLE_CONTENT = 422,
  TOO_EARLY = 425,
  TOO_MANY_REQUESTS = 429,

  SERVER_ERROR = 500,
  SERVICE_UNAVAILABLE = 503,
}
